Update code remove load GPU

diff --git a/Dockerfile.pytorch b/Dockerfile.pytorch
--- a/Dockerfile.pytorch
+++ b/Dockerfile.pytorch
@@ -31,8 +31,8 @@ RUN apt-get update && \
     libgl1 libglib2.0-0 libsm6 libxext6 libxrender1 && \
     rm -rf /var/lib/apt/lists/*
 
-
-RUN conda install -c "nvidia/label/cuda-12.4" cuda -y
+#
+RUN #conda install -c "nvidia/label/cuda-12.4" cuda -y
 ENV CUDA_HOME=/opt/conda \
     TORCH_CUDA_ARCH_LIST="6.0;6.1;7.0;7.5;8.0;8.6+PTX;8.9;9.0"
 
@@ -53,7 +53,15 @@ WORKDIR /app
 
 COPY . ./
 
+
 ENV PYTHONPATH=/app
+
+ENV NVIDIA_VISIBLE_DEVICES=all \
+    NVIDIA_DRIVER_CAPABILITIES=compute,utility,video \
+    CUDA_VISIBLE_DEVICES=all
+
+#HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
+#    CMD nvidia-smi || exit 1
 
 # Change permissions for start.sh
 RUN chmod +x /app/start.sh
